# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'Workspace.xcworkspace'

target 'App' do
  project 'App/App.xcodeproj'
  use_frameworks!
  pod 'Visuality'
  pod 'Frame'
  pod 'Pixels'
  pod 'Hammer'
  pod 'PinLayout'
  #pod 'RealmSwift'
end
