workspace 'Workspace.xcworkspace'

target 'App' do
  project 'App/App.xcodeproj'
  platform :ios, '11.0'
  use_frameworks!
  pod 'Visuality'
  pod 'Frame'
  pod 'Pixels'
  pod 'Hammer'
  #pod 'PinLayout'
  #pod 'Hero'
  #pod 'RealmSwift'
end
